name: API-TESTS-Frisby

on:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm

      - name: Npm Install
        run: npm ci
      - name: Secret
        run: echo "${{ secrets.API_KEY }} secret"
      - name: Token
        run: echo "${{ secrets.ACCESS_TOKEN }} secret"
      - name: Run Tests
        run: npm run test
        env: 
          API_KEY: ${{ secrets.API_KEY }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}




# name: Api-Tests
# on: [push]
# env: 
#   API_KEY: ${{ secrets.API_KEY }}
#   ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
# jobs:
#   Test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Setup Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 16.13.x
#           cache: npm
#       - name: Npm Install
#         run: npm ci
#       - name: Secret
#         run: echo  "${{ secrets.API_KEY }} secret"
#       - name: Token
#         run: token "${{ secrets.ACCESS_TOKEN }} secret"
#       - name: Run Tests
#         run: npm run test
        
